Use type specific entity retrieval to replace predicates
jellysquid3/Lithium pull request #43
Opened 2020-05-13 23:07 UTC by 2No2Name

In some places predicates are used to filter entities by type (armorstand cramming with minecarts, itemframes/paintings colliding with each other, llamas trying to find other llamas for caravans). With many entities of a different type nearby, evaluating the predicate on them wastes a lot of CPU time. Vanilla already provides a way to get only entities of a certain class, and making use of this method (adapted to allow excluding one entity) improves the performance a lot in certain configurations.

In my test with a 101x101 grid of armorstands standing on the ground, this optimization brought the 186mspt down to 145mspt. Of course that test is not a real gameplay situation, but it shows that getting entities of the wrong type and evaluating the predicate costs a lot of performance.

2020-05-14 18:21 UTC, jellysquid3 requested changes

2020-05-14 18:21 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/lithium/common/world/WorldHelper.java
> +                WorldChunk worldChunk = chunkManager.getWorldChunk(m, n, false);
These names should be de-obfuscated.

2020-05-14 18:21 UTC, jellysquid3 commented on src/main/java/me/jellysquid/mods/lithium/common/world/WorldHelper.java
> +        for(int k = i; k <= j; ++k) {
More obfuscated names.

2020-05-17 10:49 UTC, 2No2Name commented on src/main/java/me/jellysquid/mods/lithium/common/world/WorldHelper.java
> +                WorldChunk worldChunk = chunkManager.getWorldChunk(m, n, false);
I deobfuscated them now

2020-05-20 03:23 UTC, jellysquid3 approved these changes

2020-07-20 01:27 UTC, 2No2Name commented
Merged after rebasing onto dev.

2020-07-20 01:27 UTC, closed without merging