Refactor world border collision
jellysquid3/Lithium pull request #6
Opened 2019-12-17 01:01 UTC by vktec

This PR moves the optimized world border collision code into the `LithiumEntityCollisions` class, which allows it to be used in the general entity collision optimizations.

2019-12-17 01:02 UTC, vktec commented
Probably a good idea to squash commits; I pushed too early

2019-12-17 04:42 UTC, liach approved these changes

2019-12-18 05:00 UTC, jellysquid3 requested changes
These changes break collisions against the world border while the player or another entity is outside of it, making it impossible to cross the planes the world border starts at. To replicate the issue, create a small world border and place the player outside of it by no-clipping with F3+N. Then, disable no-clip and try to move around one corner of the world border (while still outside of it.)

2019-12-24 04:21 UTC, jellysquid3 commented
Apologies. The issues I've detailed above are not a result of your implementation and are instead rather edge cases in the original implementation that only occurred in some situations. I've since fixed it and have replaced the calls to `VoxelShapes#matchesAnywhere(...)` in `getBlockCollisions` with our own.

2019-12-24 04:21 UTC, closed without merging